# Generated by Django 4.2.1 on 2023-06-06 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('script', models.CharField(choices=[('players', 'players'), ('scraper', 'scraper')], max_length=50)),
                ('changes_detected', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('enlace', models.URLField()),
                ('temporada', models.CharField(max_length=10)),
                ('fecha', models.CharField(max_length=20)),
                ('ultimo_club', models.CharField(max_length=100)),
                ('nuevo_club', models.CharField(max_length=100)),
                ('valor_mercado', models.CharField(max_length=20)),
                ('coste', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='TransferList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('transfers', models.ManyToManyField(to='api.transfer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
